#!/usr/bin/python
# -*- coding: utf-8 -*-

import pycommentator

def printdoc(obj):
    if obj['doc']:
        print obj['doc']

def docargs(obj):
    args=[]
    if obj['args'][0]:
        if obj['args'][3]:
            args+=obj['args'][0][:-1*len(obj['args'][3])]
            args+=['%s=%s' % x for x in zip(obj['args'][0], obj['args'][3])]
        else:
            args=obj['args'][0]
    if obj['args'][1]:
        args.append('*%s' % obj['args'][1])
    if obj['args'][2]:
        args.append('**%s' % obj['args'][2])
    return ', '.join(args)

def printmarkdown(docs):
    
    ### THE HEADER
    print docs['name']
    printdoc(docs)
    
    # Module functions first
    if docs['functions']:
        print '# Functions'
        for function in docs['functions']:
            print '## %s' % function['name']
            printdoc(function)
            print docargs(function)
    # Module classes
    if docs['classes']:
        print '# Classes'
        for classie in docs['classes']:
            print '## %s' % classie['name']
            printdoc(classie)
    


def main(argv):
    if len(argv)<2:
        print 'Error: No module defined'
        print 'Usage: %s <module>' % sys.argv[0]
    elif len(argv)>2:
        print 'Error: Only one module accepted'
        print 'Usage: %s <module>' % sys.argv[0]
    else:
        docs = pycommentator.docs(argv[1])
    
    printmarkdown(docs)


if __name__ == '__main__':
    import sys
    main(sys.argv)